lab4/Project/HeatEnergyConsumption/Models/Manager.cs
namespace HeatEnergyConsumption.Models
{
    public partial class Manager
    {
        public Manager()
        {
            Organizations = new HashSet<Organization>();
        }

        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public string Surname { get; set; } = null!;
        public string? MiddleName { get; set; }
        public string PhoneNumber { get; set; } = null!;

        public virtual ICollection<Organization> Organizations { get; set; }
    }
}

lab4/Project/HeatEnergyConsumption/Models/Organization.cs
namespace HeatEnergyConsumption.Models
{
    public partial class Organization
    {
        public Organization()
        {
            ChiefPowerEngineers = new HashSet<ChiefPowerEngineer>();
            HeatEnergyConsumptionRates = new HashSet<HeatEnergyConsumptionRate>();
            ProducedProducts = new HashSet<ProducedProduct>();
            ProvidedServices = new HashSet<ProvidedService>();
        }

        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public int OwnershipFormId { get; set; }
        public string Address { get; set; } = null!;
        public int? ManagerId { get; set; }

        public virtual Manager? Manager { get; set; }
        public virtual OwnershipForm OwnershipForm { get; set; } = null!;
        public virtual ICollection<ChiefPowerEngineer> ChiefPowerEngineers { get; set; }
        public virtual ICollection<HeatEnergyConsumptionRate> HeatEnergyConsumptionRates { get; set; }
        public virtual ICollection<ProducedProduct> ProducedProducts { get; set; }
        public virtual ICollection<ProvidedService> ProvidedServices { get; set; }
    }
}

lab4/Project/HeatEnergyConsumption/Models/OwnershipForm.cs
namespace HeatEnergyConsumption.Models
{
    public partial class OwnershipForm
    {
        public OwnershipForm()
        {
            Organizations = new HashSet<Organization>();
        }

        public int Id { get; set; }
        public string Name { get; set; } = null!;

        public virtual ICollection<Organization> Organizations { get; set; }
    }
}

lab4/Project/HeatEnergyConsumption/Controllers/ManagersController.cs
using Microsoft.AspNetCore.Mvc;
using HeatEnergyConsumption.Data;
using HeatEnergyConsumption.Models;

namespace HeatEnergyConsumption.Controllers
{
	public class ManagersController : Controller
	{
		readonly HeatEnergyConsumptionContext dbContext;

		public ManagersController(HeatEnergyConsumptionContext dbContext) =>
			this.dbContext = dbContext;

		[ResponseCache(CacheProfileName = "Caching")]
		public IActionResult Table()
		{
			IEnumerable<Manager> records = dbContext.Managers.OrderBy(record => record.Id);
			return View(records);
		}
	}
}

lab4/Project/HeatEnergyConsumption/Controllers/OrganizationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HeatEnergyConsumption.Data;
using HeatEnergyConsumption.Models;

namespace HeatEnergyConsumption.Controllers
{
	public class OrganizationsController : Controller
	{
		readonly HeatEnergyConsumptionContext dbContext;

		public OrganizationsController(HeatEnergyConsumptionContext dbContext) =>
			this.dbContext = dbContext;

		[ResponseCache(CacheProfileName = "Caching")]
		public IActionResult Table()
		{
			IEnumerable<Organization> records = dbContext.Organizations
				.Include(record => record.OwnershipForm)
				.Include(record => record.Manager)
				.OrderBy(record => record.Id);
			return View(records);
		}
	}
}

lab4/Project/HeatEnergyConsumption/Controllers/OwnershipFormsController.cs
using Microsoft.AspNetCore.Mvc;
using HeatEnergyConsumption.Models;
using HeatEnergyConsumption.Data;

namespace HeatEnergyConsumption.Controllers
{
    public class OwnershipFormsController : Controller
    {
        readonly HeatEnergyConsumptionContext dbContext;

        public OwnershipFormsController(HeatEnergyConsumptionContext dbContext) =>
            this.dbContext = dbContext;

		[ResponseCache(CacheProfileName = "Caching")]
		public IActionResult Table()
        {
            IEnumerable<OwnershipForm> records = dbContext.OwnershipForms.OrderBy(record => record.Id);
            return View(records);
        }
    }
}

lab4/Project/HeatEnergyConsumption/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

lab4/Project/HeatEnergyConsumption/Views/Managers/Table.cshtml
@model IEnumerable<HeatEnergyConsumption.Models.Manager>

@{
	ViewData["Title"] = "Руководители";
}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<title>@ViewData["Title"]</title>
		<link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
	</head>
	<body>
		<h2 class="header">@ViewData["Title"]</h2>
		<br/>

		<table class="table">
			<thead>
				<tr>
					<th>ID</th>
					<th>Фамилия</th>
					<th>Имя</th>
					<th>Отчество</th>
					<th>Номер телефона</th>
				</tr>
			</thead>
			<tbody>
				@foreach (Manager record in Model)
				{
					<tr>
						<td>@record.Id</td>
						<td>@record.Surname</td>
						<td>@record.Name</td>
						<td>@record.MiddleName</td>
						<td>@record.PhoneNumber</td>
					</tr>
				}
			</tbody>
		</table>
	</body>
</html>

lab4/Project/HeatEnergyConsumption/Views/OwnershipForms/Table.cshtml
@model IEnumerable<HeatEnergyConsumption.Models.OwnershipForm>

@{
	ViewData["Title"] = "Формы собственности";
}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<title>@ViewData["Title"]</title>
		<link rel="stylesheet" href="~/css/style.css" asp-append-version="true"/>
	</head>
	<body>
		<h2 class="header">@ViewData["Title"]</h2>
		<br/>

		<table class="table">
			<thead>
				<tr>
					<th>ID</th>
					<th>Название</th>
				</tr>
			</thead>
			<tbody>
				@foreach (OwnershipForm record in Model)
				{
					<tr>
						<td>@record.Id</td>
						<td>@record.Name</td>
					</tr>
				}
			</tbody>
		</table>
	</body>
</html>

lab4/Project/HeatEnergyConsumption/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HeatEnergyConsumption</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HeatEnergyConsumption.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Потребление теплоэнергии</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OwnershipForms" asp-action="Table">Формы собственности</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Managers" asp-action="Table">Руководители</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Organizations" asp-action="Table">Организации</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HeatEnergyConsumption - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>